spring.application.name=backendsystem

# 1. The clean JDBC URL (Starts with jdbc: and has no passwords inside it!)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0

# 2. Your Exact Username
spring.datasource.username=postgres.nvyfpuipknqattpfrgmk

# 3. Your Password (replace 'mypassword' with your real one if needed)
spring.datasource.password=MyPassword

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true