package com.smartTaskAndResourcePlanner.backendsystem.controllers;

import com.smartTaskAndResourcePlanner.backendsystem.models.User;
import com.smartTaskAndResourcePlanner.backendsystem.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.crypto.password.PasswordEncoder; // 1. IMPORT THE ENCODER
import org.springframework.web.bind.annotation.*;

import java.util.Map;
import java.util.Optional;

@RestController
@RequestMapping("/api/auth")
@CrossOrigin(origins = "*")
public class AuthController {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private PasswordEncoder passwordEncoder; // 2. INJECT THE ENCODER BEAN

    // registration endpoint
    @PostMapping("/register")
    public ResponseEntity<?> registerUser(@RequestBody User newUser){
        // clean inputs
        if(newUser.getUsername() == null || newUser.getUsername().trim().isEmpty() ||
                newUser.getPassword() == null || newUser.getPassword().trim().isEmpty()){
            return ResponseEntity.badRequest().body(Map.of("message","Username and password cannot be empty"));
        }

        // checking for username already existing in supabase
        Optional<User> existingUser = userRepository.findByUsername(newUser.getUsername().trim());
        if(existingUser.isPresent()){
            return ResponseEntity.status(HttpStatus.CONFLICT).body(Map.of("message","Username already taken"));
        }

        newUser.setUsername(newUser.getUsername().trim());

        // 3. SECURE HASHING: Encrypt the password before sending it to Supabase
        String hashedPassword = passwordEncoder.encode(newUser.getPassword());
        newUser.setPassword(hashedPassword);

        // saving the new user with the encrypted password
        User savedUser = userRepository.save(newUser);

        return ResponseEntity.status(HttpStatus.CREATED).body(Map.of(
                "message", "Registration successful",
                "userId", savedUser.getId()
        ));
    }

    // login endpoint
    @PostMapping("/login")
    public ResponseEntity<?> loginUser(@RequestBody User loginRequest){
        // look for user by username
        Optional<User> userOpt = userRepository.findByUsername(loginRequest.getUsername().trim());

        if(userOpt.isPresent()){
            User user = userOpt.get();

            // 4. SECURE VERIFICATION: Use .matches() to check the incoming password against the hash
            if(passwordEncoder.matches(loginRequest.getPassword(), user.getPassword())){
                return ResponseEntity.ok(Map.of(
                        "message", "Login successful",
                        "userId", user.getId(),
                        "username", user.getUsername()
                ));
            }
        }
        // if username does not exist or password does not match return an unauthorized status
        return ResponseEntity.status(HttpStatus.UNAUTHORIZED).body(Map.of("message", "Invalid username or password"));
    }

    //this receives the unique token generated by the browser
    //finds the user by thier id
    //and updates the fcm_token column inside supabase
    @PutMapping("/update-fcm-token")
    public ResponseEntity<?> updateFcmToken(@RequestParam Long userId, @RequestParam String token) {
        Optional<User> userOpt = userRepository.findById(userId);

        if (userOpt.isPresent()) {
            User user = userOpt.get();

            // Adds the incoming device token without deleting the existing ones!
            user.getFcmTokens().add(token);
            userRepository.save(user);

            System.out.println("💾 MULTI-DEVICE: Synchronized token into device collection list for user: " + user.getUsername());
            return ResponseEntity.ok(Map.of("message", "Device token synchronized successfully."));
        }

        return ResponseEntity.status(HttpStatus.NOT_FOUND).body(Map.of("message", "User tracking ID not found."));
    }
}